export default{
    curUserinfo(context,list){
        context.commit('curUserinfo',list)
    },
    removeUserinfo(context){
        context.commit('removeUserinfo')
    },
    addCart(context,info){
        context.commit('addCart',info)
    },
    removeShopcart(context){
        context.commit('removeShopcart')
    },
    init_shopcart(context,list){
        context.commit('init_shopcart',list)
    },
    addshopnum(context,id){
        context.commit('addshopnum',id)
    },
    subshopnum(context,id){
        context.commit('subshopnum',id)
    },
    changeChecked(context,id){
        context.commit('changeChecked',id)
    },
    addDeliveryaddress(context,list){
        context.commit('addDeliveryaddress',list)
    },
    editDeliveryaddress(context,list){
        context.commit('editDeliveryaddress',list)
    },
    deleteDeliveryaddress(context,id){
        context.commit('deleteDeliveryaddress',id)
    },
    init_deliveryaddress(context,arr){
        context.commit('init_deliveryaddress',arr)
    },
}